soclone/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from soclone.models import Answer, Question

urlpatterns = patterns('soclone.views',
    url(r'^$',                                           'index',              name='index'),
    url(r'^about/$',                                     'about',              name='about'),
    url(r'^faq/$',                                       'faq',                name='faq'),
    url(r'^search/$',                                    'search',             name='search'),
    url(r'^login/$',                                     'login',              name='login'),
    url(r'^logout/$',                                    'logout',             name='logout'),
    url(r'^questions/$',                                 'questions',          name='questions'),
    url(r'^questions/ask/$',                             'ask_question',       name='ask_question'),
    url(r'^questions/tagged/(?P<tag_name>[^/]+)/$',      'tag',                name='tag'),
    url(r'^questions/(?P<question_id>\d+)/answer/$',     'add_answer',         name='add_answer'),
    url(r'^questions/(?P<question_id>\d+)/close/$',      'close_question',     name='close_question'),
    url(r'^questions/(?P<question_id>\d+)/edit/$',       'edit_question',      name='edit_question'),
    url(r'^questions/(?P<question_id>\d+)/delete/$',     'delete_question',    name='delete_question'),
    url(r'^questions/(?P<question_id>\d+)/favourite/$',  'favourite_question', name='favourite_question'),
    url(r'^questions/(?P<question_id>\d+)/revisions/$',  'question_revisions', name='question_revisions'),
    url(r'^questions/(?P<object_id>\d+)/comment/$',      'add_comment',        name='add_question_comment', kwargs={'model': Question}),
    url(r'^questions/(?P<object_id>\d+)/flag/$',         'flag_item',          name='flag_question', kwargs={'model': Question}),
    url(r'^questions/(?P<object_id>\d+)/vote/$',         'vote',               name='vote_on_question', kwargs={'model': Question}),
    url(r'^questions/(?P<question_id>\d+)/(?:[^/]+/)?$', 'question',           name='question'),
    url(r'^unanswered/$',                                'unanswered',         name='unanswered'),
    url(r'^answers/(?P<answer_id>\d+)/$',                'answer_comments',    name='answer'),
    url(r'^answers/(?P<answer_id>\d+)/accept/$',         'accept_answer',      name='accept_answer'),
    url(r'^answers/(?P<answer_id>\d+)/edit/$',           'edit_answer',        name='edit_answer'),
    url(r'^answers/(?P<answer_id>\d+)/revisions/$',      'answer_revisions',   name='answer_revisions'),
    url(r'^answers/(?P<object_id>\d+)/comment/$',        'add_comment',        name='add_answer_comment', kwargs={'model': Answer}),
    url(r'^answers/(?P<object_id>\d+)/flag/$',           'flag_item',          name='flag_answer', kwargs={'model': Answer}),
    url(r'^answers/(?P<object_id>\d+)/vote/$',           'vote',               name='vote_on_answer', kwargs={'model': Answer}),
    url(r'^comments/(?P<comment_id>\d+)/delete/$',       'delete_comment',     name='delete_comment'),
    url(r'^tags/$',                                      'tags',               name='tags'),
    url(r'^users/$',                                     'users',              name='users'),
    url(r'^users/(?P<user_id>\d+)/(?:[^/]+/)?$',         'user',               name='user'),
    url(r'^badges/$',                                    'badges',             name='badges'),
    url(r'^badges/(?P<badge_id>\d+)/(?:[^/]+/)?$',       'badge',              name='badge'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

soclone/models.py
"""SOClone Models."""
import collections
import datetime
import hashlib
import re

from django.contrib.auth.models import User, UserManager
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import connection, models, transaction
from django.db.models import Q
from django.db.models.signals import post_delete, post_save, pre_save
from django.template.defaultfilters import slugify
from django.utils import simplejson

from soclone.utils.lists import flatten

class TagManager(models.Manager):
    UPDATE_USE_COUNTS_QUERY = (
        'UPDATE soclone_tag '
        'SET use_count = ('
            'SELECT COUNT(*) FROM soclone_question_tags '
            'WHERE tag_id = soclone_tag.id'
        ') '
        'WHERE id IN (%s)')

    def get_or_create_multiple(self, names, user):
        """
        Fetches a list of Tags with the given names, creating any Tags
        which don't exist when necesssary.
        """
        tags = list(self.filter(name__in=names))
        if len(tags) < len(names):
            existing_names = set(tag.name for tag in tags)
            new_names = [name for name in names if name not in existing_names]
            tags.extend([self.create(name=name, created_by=user)
                         for name in new_names])
        return tags

    def update_use_counts(self, tags):
        """Updates the given Tags with their current use counts."""
        if not tags:
            return
        cursor = connection.cursor()
        query = self.UPDATE_USE_COUNTS_QUERY % ','.join(['%s'] * len(tags))
        cursor.execute(query, [tag.id for tag in tags])
        transaction.commit_unless_managed()

class Tag(models.Model):
    """A tag for Questions."""
    name       = models.CharField(max_length=24, unique=True)
    created_by = models.ForeignKey(User, related_name='created_tags')
    # Denormalised data
    use_count = models.PositiveIntegerField(default=0)

    objects = TagManager()

    class Meta:
        ordering = ('-use_count', 'name')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag', args=[self.name])

class QuestionManager(models.Manager):
    def update_tags(self, question, tagnames, user):
        """
        Updates Tag associations for a question to match the given
        tagname string.

        Returns ``True`` if tag usage counts were updated as a result,
        ``False`` otherwise.
        """
        current_tags = list(question.tags.all())
        current_tagnames = set(t.name for t in current_tags)
        updated_tagnames = set(t for t in tagnames.split(' ') if t)
        modified_tags = []

        removed_tags = [t for t in current_tags
                        if t.name not in updated_tagnames]
        if removed_tags:
            modified_tags.extend(removed_tags)
            question.tags.remove(*removed_tags)

        added_tagnames = updated_tagnames - current_tagnames
        if added_tagnames:
            added_tags = Tag.objects.get_or_create_multiple(added_tagnames,
                                                            user)
            modified_tags.extend(added_tags)
            question.tags.add(*added_tags)

        if modified_tags:
            Tag.objects.update_use_counts(modified_tags)
            return True

        return False

    def update_answer_count(self, question):
        """
        Executes an UPDATE query to update denormalised data with the
        number of answers the given question has.
        """
        self.filter(id=question.id).update(
            answer_count=Answer.objects.for_question(question).count())

class Question(models.Model):
    CLOSE_REASONS = (
        (1, u'Exact duplicate'),
        (2, u'Not programming related'),
        (3, u'Subjective and argumentative'),
        (4, u'Not a real question'),
        (5, u'Blatantly offensive'),
        (6, u'No longer relevant'),
        (7, u'Too localized'),
        (8, u'Spam'),
    )

    """A question."""
    title    = models.CharField(max_length=300)
    author   = models.ForeignKey(User, related_name='questions')
    added_at = models.DateTimeField(default=datetime.datetime.now)
    tags     = models.ManyToManyField(Tag, related_name='questions')
    # Status
    wiki            = models.BooleanField(default=False)
    wikified_at     = models.DateTimeField(null=True, blank=True)
    answer_accepted = models.BooleanField(default=False)
    closed          = models.BooleanField(default=False)
    closed_by       = models.ForeignKey(User, null=True, blank=True, related_name='closed_questions')
    closed_at       = models.DateTimeField(null=True, blank=True)
    close_reason    = models.SmallIntegerField(choices=CLOSE_REASONS, null=True, blank=True)
    deleted         = models.BooleanField(default=False)
    deleted_at      = models.DateTimeField(null=True, blank=True)
    deleted_by      = models.ForeignKey(User, null=True, blank=True, related_name='deleted_questions')
    locked          = models.BooleanField(default=False)
    locked_by       = models.ForeignKey(User, null=True, blank=True, related_name='locked_questions')
    locked_at       = models.DateTimeField(null=True, blank=True)
    # Denormalised data
    score                = models.IntegerField(default=0)
    answer_count         = models.PositiveIntegerField(default=0)
    comment_count        = models.PositiveIntegerField(default=0)
    view_count           = models.PositiveIntegerField(default=0)
    offensive_flag_count = models.SmallIntegerField(default=0)
    favourite_count      = models.PositiveIntegerField(default=0)
    last_edited_at       = models.DateTimeField(null=True, blank=True)
    last_edited_by       = models.ForeignKey(User, null=True, blank=True, related_name='last_edited_questions')
    last_activity_at     = models.DateTimeField()
    last_activity_by     = models.ForeignKey(User, related_name='last_active_in_questions')
    tagnames             = models.CharField(max_length=125)
    summary              = models.CharField(max_length=180)
    html                 = models.TextField()

    objects = QuestionManager()

    def save(self, **kwargs):
        """
        Overridden to manually manage addition of tags when the object
        is first saved.

        This is required as we're using ``tagnames`` as the sole means of
        adding and editing tags.
        """
        initial_addition = (self.id is None)
        super(Question, self).save(**kwargs)
        if initial_addition:
            tags = Tag.objects.get_or_create_multiple(self.tagname_list(),
                                                      self.author)
            self.tags.add(*tags)
            Tag.objects.update_use_counts(tags)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return '%s%s/' % (reverse('question', args=[self.id]),
                          slugify(self.title))

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_latest_revision(self):
        """Convenience method to grab the latest revision."""
        return self.revisions.all()[0]

    def tagname_list(self):
        """Creates a list of Tag names from the ``tagnames`` attribute."""
        return [name for name in self.tagnames.split(u' ')]

class QuestionRevision(models.Model):
    """A revision of a Question."""
    question   = models.ForeignKey(Question, related_name='revisions')
    revision   = models.PositiveIntegerField(blank=True)
    title      = models.CharField(max_length=300)
    author     = models.ForeignKey(User, related_name='question_revisions')
    revised_at = models.DateTimeField()
    tagnames   = models.CharField(max_length=125)
    summary    = models.CharField(max_length=300, blank=True)
    text       = models.TextField()

    class Meta:
        ordering = ('-revision',)

    def save(self, **kwargs):
        """Looks up the next available revision number."""
        if not self.revision:
            self.revision = QuestionRevision.objects.filter(
                question=self.question).values_list('revision',
                                                    flat=True)[0] + 1
        super(QuestionRevision, self).save(**kwargs)

    def __unicode__(self):
        return u'revision %s of %s' % (self.revision, self.title)

class FavouriteQuestion(models.Model):
    """A favourite Question of a User."""
    question      = models.ForeignKey(Question)
    user          = models.ForeignKey(User)
    favourited_at = models.DateTimeField(default=datetime.datetime.now)

def update_question_favourite_count(instance, **kwargs):
    """
    Updates the favourite count for the Question related to the given
    FavouriteQuestion.
    """
    if kwargs.get('raw', False):
        return
    cursor = connection.cursor()
    cursor.execute(
        'UPDATE soclone_question SET favourite_count = ('
            'SELECT COUNT(*) from soclone_favouritequestion '
            'WHERE soclone_favouritequestion.question_id = soclone_question.id'
        ') '
        'WHERE id = %s', [instance.question_id])
    transaction.commit_unless_managed()

post_save.connect(update_question_favourite_count, sender=FavouriteQuestion)
post_delete.connect(update_question_favourite_count, sender=FavouriteQuestion)

class AnswerManager(models.Manager):
    def for_question(self, question, user=None):
        """
        Retrieves visibile answers for the given question. Delete answers
        are only visibile to the person who deleted them.
        """
        if user is None or not user.is_authenticated():
            return self.filter(question=question, deleted=False)
        else:
            return self.filter(Q(question=question),
                               Q(deleted=False) | Q(deleted_by=user))

class Answer(models.Model):

soclone/templates/answer.html
{% load soclone_tags %}
<div id="answer-comments-container-{{ answer.id }}" class="comments-container">
  {% for comment in comments %}
  <div class="comment" id="answer-comment-{{ comment.id }}">
  {{ comment.comment }} - <a href="{% url user comment.user_id %}" class="comment-user">{{ comment.user_username }}</a>
  <span class="comment-date">({{ comment.added_at|timesince }} ago)</span>
  {% if user|can_delete_comment:comment %}
  <a href="{% url delete_comment comment.id %}" class="comment-delete" id="comment-delete-{{ comment.id }}" title="remove this comment">
    <img src="{{ MEDIA_ROOT }}img/close-small.png" alt="remove">
  </a>
  {% endif %}
  </div>
  {% endfor %}
  <form class="comment" id="answer-add-comment-{{ question.id }}" action="{% url add_answer_commment answer.id %}" method="POST">
    {% csrf_token %}
    <div>
      {{ comment_form.comment }} <input type="submit" value="Add Comment">
    </div>
  </form>
</div>

soclone/templates/badge.html
{% extends "base.html" %}
{% load soclone_tags list_tags %}
{% load list_tags %}

{% block bodyclass %}badges{% endblock %}

{% block content %}
<div id="badge">
  <p><span class="badge"><span class="badge{{ badge.type }}">&bull;</span> {{ badge.name }}</span> {{ badge.description }}.{% if badge.multiple %} This badge can be awarded multiple times.{% endif %}</p>
  <div class="user-lists">
  {% for recipient_list in awarded_to|in_batches:"4" %}
    {% if recipient_list %}
    <div class="user-list">
      {% for recipient in recipient_list %}
      <a href="{% url user recipient.id %}{{ recipient.username }}/">{{ recipient.username }}</a> {% reputation recipient %}
      {% endfor %}
    </div>
    {% endif %}
  {% endfor %}
  </div>
</div>
{% endblock %}

soclone/templates/base_2col.html
{% extends "base.html" %}
{% block content %}
<div id="main">
{% block main %}{% endblock %}
</div>

<div id="sidebar">
{% block sidebar %}{% endblock %}
</div>
{% endblock %}

soclone/templates/edit_answer.html
{% extends "base_2col.html" %}
{% load html %}

{% block bodyclass %}questions{% endblock %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/prettify.css" media="screen">
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/textarearesizer.css" media="screen">
<script type="text/javascript" src="{{ MEDIA_URL }}js/wmd/wmd.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/typewatch-2.0.0.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/textarearesizer-1.0.4.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/prettify.js"></script>
<script type="text/javascript">
$(function()
{
    $("#id_text").typeWatch({highlight: false, wait: 3000,
                             captureLength: 5, callback: SOClone.styleCode});
    $("#id_text:not(.processed)").TextAreaResizer();
});
</script>
{% endblock %}

{% block pageheader_title %}{{ block.super }} [<a href="{{ answer.get_absolute_url }}">Return to Answer</a>]{% endblock %}

{% block main %}
<form id="answer-form" method="POST" action="{% url edit_answer answer.id %}">
  {% csrf_token %}
  <div class="form-item">
    {{ revision_form.revision.label_tag }}
    {% if revision_form.revision.errors %}{{ revision_form.revision.errors.as_ul }}{% endif %}
    {% field revision_form.revision style="width: 575px" %} <input type="submit" name="select_revision" value="Select">
  </div>
  <div class="form-item">
    {% if form.text.errors %}{{ form.text.errors.as_ul }}{% endif %}
    <div class="resizable-textarea">
    {% field form.text %}
    </div>
    {% if form.wiki %}{% field form.wiki %} {{ form.wiki.label_tag }}{% endif %}
  </div>
  <div class="form-item">
    <div class="wmd-preview text">{% if preview %}{{ preview }}{% endif %}</div>
  </div>
  <div class="form-item">
    {{ form.summary.label_tag }}
    {% if form.summary.errors %}{{ form.summary.errors.as_ul }}{% endif %}
    {% field form.summary size="60" %}
    <p class="help">Briefly describe your changes (corrected spelling, fixed grammar, improved formatting etc.)</p>
  </div>
  <div class="form-submit">
    <input type="submit" name="submit" value="Save Your Edits">
    <input type="submit" name="preview" id="preview-button" value="Preview">
  </div>
</form>
{% endblock %}

{% block sidebar %}
<div class="module">
  <h4>Good Edits</h4>
  <p>Fix grammatical or spelling errors.</p>
  <p>Clarify meaning without changing it.</p>
  <p>Correct minor mistakes.</p>
  <p>Add related resources or links.</p>
  <p><em>Always</em> respect the original author.</p>
</div>
<div class="module">
  <h4>Markdown Quick Reference</h4>
  <p>indent <code>code</code> by 4 spaces</p>
  <p>don't want colorization? Use &lt;pre&gt;</p>
  <p>to linebreak use 2 spaces at end</p>
  <p>&gt; blockquote</p>
  <p>backtick escapes <code>`like this`</code></p>
  <p>&lt;http://foo.com&gt;<br>[foo](http://foo.com)<br>&lt;a href="http://foo.com"&gt;foo&lt;/a&gt;</p>
</div>
{% endblock %}

soclone/templates/question.html
{% extends "base_2col.html" %}
{% load html soclone_tags %}

{% block bodyclass %}questions question{% endblock %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/prettify.css" media="screen">
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/textarearesizer.css" media="screen">
<script type="text/javascript" src="{{ MEDIA_URL }}js/wmd/wmd.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/typewatch-2.0.0.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/textarearesizer-1.0.4.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/prettify.js"></script>
<script type="text/javascript">
$(function()
{
    $("#id_text").typeWatch({highlight: false, wait: 3000,
                             captureLength: 5, callback: SOClone.styleCode});
    $("#id_text:not(.processed)").TextAreaResizer();
    SOClone.styleCode();
});
</script>
{% endblock %}

{% block main %}
<div id="question">
  <div class="vote">
    <form class="vote" id="question-up-{{ question.id }}" action="{% url vote_on_question question.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="type" value="up">
      <input type="image" id="question-uparrow-{{ question.id }}"
             src="{{ MEDIA_URL }}img/vote-arrow-up{% if question_vote and question_vote.is_upvote %}-on{% endif %}.png"
             alt="{% if question_vote and question_vote.is_upvote %}Undo Up Vote{% else %}Vote Up{% endif %}">
    </form>
    <span class="score" id="question-score-{{ question.id }}">{{ question.score }}</span>
    <form class="vote" id="question-down-{{ question.id }}" action="{% url vote_on_question question.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="type" value="down">
      <input type="image" id="question-downarrow-{{ question.id }}"
             src="{{ MEDIA_URL }}img/vote-arrow-down{% if question_vote and question_vote.is_downvote %}-on{% endif %}.png"
             alt="{% if question_vote and question_vote.is_downvote %}Undo Down Vote{% else %}Vote Down{% endif %}">
    </form>
    <form class="favourite" id="question-favourite-{{ question.id }}" action="{% url favourite_question question.id %}" method="POST">
      {% csrf_token %}
      <input type="image" id="question-star-{{ question.id }}"
             src="{{ MEDIA_URL }}img/favourite{% if favourite %}-on{% endif %}.png"
             alt="{% if favourite %}Remove{% else %}Add{% endif %} Favourite">
      {% if question.favourite_count %}<strong>{{ question.favourite_count }}</strong>{% endif %}
    </form>
  </div>
  <div class="content">
    <div class="text">
    {{ question.html|safe }}
    </div>
    <div class="tags">
      {% for tag in question.tagname_list %}
      <a href="{% url tag tag %}" class="tag" title="show questions tagged '{{ tag }}'" rel="tag">{{ tag}}</a>
      {% endfor %}
    </div>
    <div class="meta">
      <div class="controls">
        {% if user|can_retag_questions %}
        <a href="{% url edit_question question.id %}" title="edit tags on this question">retag</a>
        <span class="link-separator">|</span>
        {% endif %}
        {% if user|can_edit_post:question %}
        <a href="{% url edit_question question.id %}" title="edit this question, or roll it back to a previous version">edit</a>
        <span class="link-separator">|</span>
        {% endif %}
        {% if user|can_close_question:question %}
        <a href="{% url close_question question.id %}" title="closes/opens question for answering; when closed, no more answers can be added">{% if not question.closed %}close{% else %}open{% endif %}</a>
        <span class="link-separator">|</span>
        {% endif %}
        <a href="{% url flag_question question.id %}" title="flag this question as offensive or spam">offensive?</a>
      </div>
      <div class="users">
        {% post_user_details question %}
      </div>
    </div>
    <div class="comments">
      <a href="?showcomments=true#question-comments-{{ question.id }}" id="question-comments-{{ question.id }}">{% if question.comment_count %}{{ question.comment_count }} comment{{ question.comment_count|pluralize }}{% else %}add comment{% endif %}</a>
      <div id="question-comments-container-{{ question.id }}" class="comments-container"></div>
    </div>
  </div>
</div>

{% if question.closed %}
<h2 class="close-reason">
  Question <span class="warning">closed</span> as "{{ question.get_close_reason_display }}"
  by <a href="{% url user question.closed_by.id %}{{ question.closed_by.username }}/">{{ question.closed_by.username }}</a>
  {{ question.closed_at|timesince }} ago
</h2>
{% endif %}

{% if page.has_other_pages %}
<div class="pagination">
  {% pager page sort=answer_sort %}
</div>
{% endif %}

<div id="answers">
  <div id="answer-header">
    <h4>{{ question.answer_count }} Answer{{ question.answer_count|pluralize }}:</h4>
    <div class="tabs">
      <a href="{% url question question.id %}?sort=oldest#answers" title="Answers in the order they were given"{% ifequal answer_sort "oldest" %} class="active"{% endifequal %}>Oldest</a>
      <a href="{% url question question.id %}?sort=newest#answers" title="Most recent answers first"{% ifequal answer_sort "newest" %} class="active"{% endifequal %}>Newest</a>
      <a href="{% url question question.id %}?sort=votes#answers" title="Answers with the most votes first"{% ifequal answer_sort "votes" %} class="active"{% endifequal %}>Votes</a>
    </div>
  </div>
  {% for answer in answers %}
  {% dict_lookup answer.id in answer_votes as vote %}
  <div class="answer{% ifequal question.author_id answer.author_id %} author-answer{% endifequal %}{% if answer.accepted %} accepted{% endif %}" id="answer-{{ answer.id }}">
    <div class="vote">
      <form class="vote" id="answer-up-{{ answer.id }}" action="{% url vote_on_answer answer.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="type" value="up">
        <input type="image" id="answer-uparrow-{{ answer.id }}"
               src="{{ MEDIA_URL }}img/vote-arrow-up{% if vote and vote.is_upvote %}-on{% endif %}.png"
               alt="{% if vote and vote.is_upvote %}Undo Up Vote{% else %}Vote Up{% endif %}">
      </form>
      <span class="score" id="answer-score-{{ answer.id }}">{{ answer.score }}</span>
      <form class="vote" id="answer-down-{{ answer.id }}" action="{% url vote_on_answer answer.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="type" value="down">
        <input type="image" id="answer-downarrow-{{ answer.id }}"
               src="{{ MEDIA_URL }}img/vote-arrow-down{% if vote and vote.is_downvote %}-on{% endif %}.png"
               alt="{% if vote and vote.is_downvote %}Undo Down Vote{% else %}Vote Down{% endif %}">
      </form>
      <form class="accept" id="accept-{{ answer.id }}" action="{% url accept_answer answer.id %}" method="POST">
        {% csrf_token %}
        <input type="image" id="acccept-tick-{{ answer.id }}"
               src="{{ MEDIA_URL }}img/accept{% if answer.accepted %}-on{% endif %}.png"
               alt="{% if answer.accepted %}Withdraw Acceptance{% else %}Accept{% endif %}">
      </form>
    </div>
    <div class="content">
      <div class="text">
      {{ answer.html|safe }}
      </div>
      <div class="meta">
        <div class="controls">
          <a href="{{ answer.get_absolute_url }}" title="permalink to this answer">link</a>
          {% if user|can_edit_post:answer %}
          <span class="link-separator">|</span>
          <a href="{% url edit_answer answer.id %}" title="edit this answer, or roll it back to a previous version">edit</a>
          {% endif %}
          <span class="link-separator">|</span>
          <a href="{% url flag_answer answer.id%}" title="flag this answer as offensive or spam">offensive?</a>
        </div>
        <div class="users">
          {% post_user_details answer %}
        </div>
      </div>
      <div class="comments">
        <a href="{{ answer.get_absolute_url }}#answer-comments-{{ answer.id }}" id="answer-comments-{{ answer.id }}">{% if answer.comment_count %}{{ answer.comment_count }} comment{{ answer.comment_count|pluralize }}{% else %}add comment{% endif %}</a>
        <div id="answer-comments-container-{{ answer.id }}" class="comments-container"></div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% if page.has_other_pages %}
<div class="pagination">
  {% pager page sort=answer_sort %}
</div>
{% endif %}

{% if not question.closed %}
<form id="answer-form" method="POST" action="{% url add_answer question.id %}">
  {% csrf_token %}
  <div class="form-item">
    <div class="resizable-textarea">
    {% field answer_form.text %}
    </div>
    {% field answer_form.wiki %} {{ answer_form.wiki.label_tag }}
  </div>
  <div class="form-item">
    <div class="wmd-preview text"></div>
  </div>
  <div class="form-submit">
    <input type="submit" name="submit" value="Post Your Answer">
    <input type="submit" name="preview" id="preview-button" value="Preview">
  </div>
</form>
{% endif %}
{% endblock %}

{% block sidebar %}
<div class="module question-sidebar">
  <p>You're viewing a single question tagged</p>
  <ol>{% for tag in tags %}
    <li>
      <a href="{{ tag.get_absolute_url }}" class="tag" title="show questions tagged '{{ tag.name }}'" rel="tag">{{ tag.name }}</a> <span class="item-multiplier">&times; {{ tag.use_count }}</span>
    </li>
  {% endfor %}</ol>
  <dl>
    <dt>asked</dt>
    <dd>{{ question.added_at|timesince }} ago</dd>
    <dt>viewed</dt>
    <dd>{{ question.view_count }} time{{ question.view_count|pluralize }}</dd>
    <dt>latest activity</dt>
    <dd>{{ question.last_activity_at|timesince }} ago</dd>
  </dl>
</div>

<div class="module related-questions">
  <h4>Related</h4>
</div>
{% endblock %}